pretrained: false
checkpoint: None
mode: train

model:
  model_name: CIRIMECG
  recurrent_layer: IndRNN
  input_channels: 3
  conv_filters:
    - 64
    - 64
    - 1
  conv_kernels:
    - 5
    - 3
    - 3
  conv_dilations:
    - 1
    - 1
    - 1
  conv_bias:
    - true
    - true
    - false
  recurrent_filters:
    - 64
    - 64
    - 0
  recurrent_kernels:
    - 3
    - 3
    - 0
  recurrent_dilations:
    - 1
    - 1
    - 0
  recurrent_bias:
    - true
    - true
    - false
  time_steps: 8
  conv_dim: 2
  num_cascades: 3
  no_dc: true
  depth: 2
  keep_prediction: true
  accumulate_predictions: true
  dimensionality: 2
  reconstruction_loss:
    l1: 1
  normalization_type: null
  unnormalize_loss_inputs: false
  unnormalize_log_outputs: false
  total_reconstruction_loss_weight: 100
  update_in_frequency: false

  train_ds:
    dataset_format: UniversalECGDataset
    dataset_function: umcu
    waveform_dir: /home/jovyan/work/raw_data/umcu_rhythm
    dataset: /home/jovyan/work/training/ECGDigitization/dataset/ECGnet_synthesis_train_dataset.csv
    transforms:
      applygain: true
      resample:
        - 500
      totensor: true
      to12lead: true
    mask_args:
      type: layouts
      accelerations:
        - random
        - 3x4
        - 3x4_1
        - 6x2
      low_ratio: 0.1
      high_ratio: 0.5
      min_block: 500
      use_seed: false
    normalization_type: null
    use_seed: false
    dataset_number_of_examples: 100000
    batch_size: 12
    shuffle: true
    num_workers: 3
    pin_memory: false
    drop_last: false
  
  validation_ds:
    dataset_format: UniversalECGDataset
    dataset_function: umcu
    waveform_dir: /home/jovyan/work/raw_data/umcu_rhythm
    dataset: /home/jovyan/work/training/ECGDigitization/dataset/ECGnet_synthesis_validation_dataset.csv
    transforms:
      applygain: true
      resample:
      - 500
      totensor: true
      to12lead: true
    mask_args:
      type: layouts
      accelerations:
      - random
      - 3x4
      - 3x4_1
      - 6x2
      low_ratio: 0.1
      high_ratio: 0.5
      min_block: 500
      use_seed: true
    normalization_type: null
    use_seed: true
    dataset_number_of_examples: -1
    batch_size: 25
    log_figures: 4
    shuffle: false
    num_workers: 10
    pin_memory: false
    drop_last: false

  optim:
    name: adamw
    lr: 1e-3
    betas:
      - 0.9
      - 0.999
    weight_decay: 1e-4
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: auto
  accelerator: gpu
  devices: [1]
  num_nodes: 1
  max_epochs: 50
  precision: 32
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 1000
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: Results/CIRIMECG/
  ema:
    enable: false
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: atommic.reconstruction.ECG
