pretrained: false
checkpoint: None
mode: train

model:
  model_name: CIRIMECG
  recurrent_layer: IndRNN
  conv_filters:
    - 64
    - 64
    - 1
  conv_kernels:
    - 5
    - 3
    - 3
  conv_dilations:
    - 1
    - 2
    - 1
  conv_bias:
    - true
    - true
    - false
  recurrent_filters:
    - 64
    - 64
    - 0
  recurrent_kernels:
    - 1
    - 1
    - 0
  recurrent_dilations:
    - 1
    - 1
    - 0
  recurrent_bias:
    - true
    - true
    - false
  depth: 2
  time_steps: 8
  conv_dim: 2
  num_cascades: 8
  no_dc: true
  keep_prediction: true
  accumulate_predictions: true
  dimensionality: 2
  reconstruction_loss: 
    l1: 1
  normalization_type: max
  unnormalize_loss_inputs: false
  unnormalize_log_outputs: false
  kspace_reconstruction_loss: false
  total_reconstruction_loss_weight: 1.0
  complex_valued_type: stacked  # stacked, complex_abs, complex_sqrt_abs
  coil_combination_method: SENSE
  ssdu: false
  n2r: false
  fft_centered: true
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  estimate_coil_sensitivity_maps_with_nn: false
  consecutive_slices: 1

  train_ds:
    dataset_format: UniversalECGDataset
    dataset_function: umcu
    waveform_dir: /home/jovyan/work/raw_data/umcu_rhythm
    dataset: /home/jovyan/work/training/ECGDigitization/dataset/ECGnet_digitization_train_dataset.csv
    transforms:
      applygain: true
      resample:
        - 500
      totensor: true
    mask_args:
      type: layouts  # the mask will be loaded from the dataset, but we need to specify the type here
      accelerations:
        - "3x4"
        - "6x2"  
        - "3x4_1"
      shift_mask: false
      use_seed: false
    use_seed: false
    batch_size: 10
    shuffle: true
    num_workers: 8
    pin_memory: false
    drop_last: false

  validation_ds:
    dataset_format: UniversalECGDataset
    dataset_function: umcu
    waveform_dir: /home/jovyan/work/raw_data/umcu_rhythm
    dataset: /home/jovyan/work/training/ECGDigitization/dataset/ECGnet_digitization_val_dataset.csv
    transforms:
      applygain: true
      resample:
        - 500
      totensor: true
    mask_args:
      type: layouts  # the mask will be loaded from the dataset, but we need to specify the type here
      accelerations:
        - "3x4"
        - "6x2"
      shift_mask: false
      use_seed: false
    use_seed: false
    batch_size: 10
    shuffle: False
    num_workers: 8
    pin_memory: false
    drop_last: false

  optim:
    name: adam
    lr: 1e-4
    betas:
      - 0.9
      - 0.999
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp_find_unused_parameters_false
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  precision: 16-mixed
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: Results/CIRIMECG/
  ema:
    enable: false
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: atommic.reconstruction.ECG
