pretrained: false
checkpoint: None
mode: test

model:
  model_name: ZF
  dimensionality: 2
  complex_valued_type: stacked  # stacked, complex_abs, complex_sqrt_abs
  coil_combination_method: RSS
  fft_centered: false
  fft_normalization: backward
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  estimate_coil_sensitivity_maps_with_nn: false
  consecutive_slices: 1

  test_ds:
    data_path: parent_data_dir/calgary-campinas_version-1.0/CC359/Raw-data/Multi-channel/12-channel/Val
    coil_sensitivity_maps_path: None
    mask_path: None
    noise_path: None
    initial_predictions_path: None
    dataset_format: cc359
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    complex_target: true
    log_images_rate: 0.0
    apply_prewhitening: false
    apply_gcc: false
    estimate_coil_sensitivity_maps: false
    coil_combination_method: RSS
    dimensionality: 2
    mask_args:
      type: none
      shift_mask: false
      use_seed: true
    partial_fourier_percentage: 0.0
    remask: false
    ssdu: false
    n2r: false
    unsupervised_masked_target: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: minmax
    kspace_normalization: false
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: true
    batch_size: 1
    shuffle: false
    num_workers: 8
    pin_memory: false
    drop_last: false

  optim:
    name: adamw
    lr: 1e-4
    betas:
      - 0.9
      - 0.999
    weight_decay: 0.0
    sched:
        name: CosineAnnealing
        min_lr: 0.0
        last_epoch: -1
        warmup_ratio: 0.1

trainer:
  strategy: ddp_find_unused_parameters_false
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  precision: 16-mixed
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: output_data_dir/atommic/REC/targets/CC359_12_channel_Val/RSS/
  ema:
      enable: false
  create_tensorboard_logger: true
  create_wandb_logger: false
