pretrained: false
checkpoint: None
mode: train

model:
  model_name: MTLRS
  joint_reconstruction_segmentation_module_cascades: 5
  task_adaption_type: multi_task_learning
  use_reconstruction_module: true
  reconstruction_module_recurrent_layer: IndRNN
  reconstruction_module_conv_filters:
    - 64
    - 64
    - 2
  reconstruction_module_conv_kernels:
    - 5
    - 3
    - 3
  reconstruction_module_conv_dilations:
    - 1
    - 2
    - 1
  reconstruction_module_conv_bias:
    - true
    - true
    - false
  reconstruction_module_recurrent_filters:
    - 64
    - 64
    - 0
  reconstruction_module_recurrent_kernels:
    - 1
    - 1
    - 0
  reconstruction_module_recurrent_dilations:
    - 1
    - 1
    - 0
  reconstruction_module_recurrent_bias:
    - true
    - true
    - false
  reconstruction_module_depth: 2
  reconstruction_module_time_steps: 8
  reconstruction_module_conv_dim: 2
  reconstruction_module_num_cascades: 1
  reconstruction_module_dimensionality: 2
  reconstruction_module_no_dc: true
  reconstruction_module_keep_prediction: true
  reconstruction_module_accumulate_predictions: true
  segmentation_module: AttentionUNet
  segmentation_module_input_channels: 1
  segmentation_module_output_channels: 4
  segmentation_module_channels: 64
  segmentation_module_pooling_layers: 2
  segmentation_module_dropout: 0.0
  segmentation_loss:
    dice: 1.0
    cross_entropy: 1.0
  dice_loss_include_background: true  # always set to true if the background is removed
  dice_loss_to_onehot_y: false
  dice_loss_sigmoid: false
  dice_loss_softmax: false
  dice_loss_other_act: none
  dice_loss_squared_pred: false
  dice_loss_jaccard: false
  dice_loss_flatten: false
  dice_loss_reduction: mean_batch
  dice_loss_smooth_nr: 1e-5
  dice_loss_smooth_dr: 1e-5
  dice_loss_batch: true
  dice_metric_include_background: true  # always set to true if the background is removed
  dice_metric_to_onehot_y: false
  dice_metric_sigmoid: false
  dice_metric_softmax: false
  dice_metric_other_act: none
  dice_metric_squared_pred: false
  dice_metric_jaccard: false
  dice_metric_flatten: false
  dice_metric_reduction: mean_batch
  dice_metric_smooth_nr: 1e-5
  dice_metric_smooth_dr: 1e-5
  dice_metric_batch: true
  segmentation_classes_thresholds: [0.5, 0.5, 0.5, 0.5]
  segmentation_activation: sigmoid
  reconstruction_loss:
    l1: 1
    ssim: 1
  kspace_reconstruction_loss: false
  total_reconstruction_loss_weight: 0.9
  total_segmentation_loss_weight: 0.1
  fft_centered: true
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  magnitude_input: false
  log_multiple_modalities: false  # log all modalities in the same image, e.g. T1, T2, T1ce, FLAIR will be concatenated
  normalization_type: minmax
  normalize_segmentation_output: true
  complex_valued_type: complex_sqrt_abs
  unnormalize_loss_inputs: false
  unnormalize_log_outputs: false
  complex_data: true
  consecutive_slices: 1
  dimensionality: 2
  coil_combination_method: SENSE
  coil_dim: 1
  estimate_coil_sensitivity_maps_with_nn: false
  ssdu: false
  n2r: false

  train_ds:
    data_path: /data/projects/utwente/recon/SKM-TEA/v1-release/json/files_recon_calib-24_train.json #/data/projects/utwente/recon/SKM-TEA/v1-release/json/files_recon_calib-24_train.json #/data/projects/recon/data/public/multitask/skm-tea/v1-release/json/files_recon_calib-24_train.json
    coil_sensitivity_maps_path: None
    mask_path: None
    noise_path: None
    initial_predictions_path: None
    dataset_format:
    - custom_masking
    - skm-tea-echo1
    - lateral
    sample_rate: 0.5
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    complex_target: true
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: gaussian2d  # the mask will be loaded from the dataset, but we need to specify the type here
      accelerations:
        - 4  # 4, 6, 8, 10, 12, 16
      shift_mask: false
      use_seed: false
    partial_fourier_percentage: 0.0
    remask: false
    ssdu: false
    n2r: false
    unsupervised_masked_target: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: minmax
    kspace_normalization: false
    fft_centered: true
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: false
    segmentations_path: /data/projects/utwente/recon/SKM-TEA/v1-release/segmentation_masks/raw-data-track/ #/data/projects/utwente/recon/SKM-TEA/v1-release/segmentation_masks/raw-data-track/  #/data/projects/recon/data/public/multitask/skm-tea/v1-release/segmentation_masks/raw-data-track
    segmentation_classes: 4
    complex_data: true
    batch_size: 1
    shuffle: true
    num_workers: 4
    pin_memory: false
    drop_last: false

  validation_ds:
    data_path: /data/projects/utwente/recon/SKM-TEA/v1-release/json/files_recon_calib-24_val.json #/data/projects/utwente/recon/SKM-TEA/v1-release/json/files_recon_calib-24_val.json  #/data/projects/recon/data/public/multitask/skm-tea/v1-release/json/files_recon_calib-24_val.json
    coil_sensitivity_maps_path: None
    mask_path: None
    noise_path: None
    initial_predictions_path: None
    dataset_format:
    - custom_masking
    - SKM-TEA-echo1
    - lateral
    sample_rate: 0.5
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    complex_target: true
    log_images_rate: 0.01
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: gaussian2d  # the mask will be loaded from the dataset, but we need to specify the type here
      accelerations:
        - 4 # 4, 6, 8, 10, 12, 16
      shift_mask: false
      use_seed: true
    partial_fourier_percentage: 0.0
    remask: false
    ssdu: false
    n2r: false
    unsupervised_masked_target: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: minmax
    kspace_normalization: false
    fft_centered: true
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: true
    segmentations_path: /data/projects/utwente/recon/SKM-TEA/v1-release/segmentation_masks/raw-data-track/ #/data/projects/utwente/recon/SKM-TEA/v1-release/segmentation_masks/raw-data-track/  #/data/projects/recon/data/public/multitask/skm-tea/v1-release/segmentation_masks/raw-data-track
    segmentation_classes: 4
    complex_data: true
    batch_size: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false

  optim:
    name: adam
    lr: 1e-4
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp_find_unused_parameters_true
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  precision: 16-mixed
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: /scratch/tmpaquaij/Results/atommic/mltrs/trained_models/SKMTEA/MTLRS_SENSE
  create_tensorboard_logger: false
  create_wandb_logger: true
  wandb_logger_kwargs:
    project: MTLRS
  files_to_copy: [ ]
